name: moodo
description: Moodo is an application that provides du'a recommendations to keep
  you in a good mood.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.0.1
  flutter_bloc: ^7.0.1
  flutter_riverpod: ^0.14.0+1
  format_indonesia: ^0.1.0
  google_nav_bar: ^5.0.3
  gradient_text: ^1.0.2
  hijri: ^2.0.3
  hydrated_bloc: ^7.0.1
  lottie: ^1.0.1
  ndialog: ^4.0.1
  path_provider: ^1.1.0
  recase: ^4.0.0
  screenshot: 0.2.0
  share: ^2.0.1
  shared_preferences: ^2.0.5
  sized_context: ^1.0.0-nullsafety
  snapping_sheet: ^3.1.0
  splash_screen_view: ^1.0.1
  webview_flutter: ^2.0.8
  animated_text_kit: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - assets/doa.json
    - assets/dzikir.json
    - assets/animation/empty.json
    - assets/animation/happy.json
    - assets/animation/netral.json
    - assets/animation/sad.json
    - assets/animation/moon.json
    - assets/animation/sun.json
    - assets/logo_horizontal.png

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Sil
      fonts:
        - asset: fonts/Scheherazade-Regular.ttf
        - asset: fonts/Scheherazade-Bold.ttf
          weight: 700
